In [8]:
import numpy as np
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding
from tensorflow.keras.preprocessing.text import text_to_word_sequence
text="해보지 않으면 해낼 수 없다."
result=text_to_word_sequence(text ,split=' ' )
print(f"원문: {text}")
print(f"토큰화: {result}")

원문: 해보지 않으면 해낼 수 없다.
토큰화: ['해보지', '않으면', '해낼', '수', '없다.']


In [9]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
        '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다',
        '토큰화 한 결과는 딥러닝에서 사용 할 수 있습니다'] 

In [10]:
from tensorflow.keras.preprocessing.text import Tokenizer

token = Tokenizer()
token.fit_on_texts(docs)

In [12]:
token.word_counts '먼저 텍스트의 각 단어를 나누어 토큰화 합니다.'

OrderedDict([('먼저', 1),
             ('텍스트의', 2),
             ('각', 1),
             ('단어를', 1),
             ('나누어', 1),
             ('토큰화', 3),
             ('합니다', 1),
             ('단어로', 1),
             ('해야', 1),
             ('딥러닝에서', 2),
             ('인식됩니다', 1),
             ('한', 1),
             ('결과는', 1),
             ('사용', 1),
             ('할', 1),
             ('수', 1),
             ('있습니다', 1)])

In [13]:
token.document_count

3

In [14]:
token.word_index

{'토큰화': 1,
 '텍스트의': 2,
 '딥러닝에서': 3,
 '먼저': 4,
 '각': 5,
 '단어를': 6,
 '나누어': 7,
 '합니다': 8,
 '단어로': 9,
 '해야': 10,
 '인식됩니다': 11,
 '한': 12,
 '결과는': 13,
 '사용': 14,
 '할': 15,
 '수': 16,
 '있습니다': 17}

In [22]:
text = '오랫동안 꿈꾸는 자는 그 꿈을 닮아간다'
text_1 = '꿈꾸는 꿈을 그 오랫동안'
token = Tokenizer()
token.fit_on_texts([text])
print('문장의 토큰화: ', token.word_index)

# 각 단어를 숫자화
x = token.texts_to_sequences([text_1])
print('문장의 숫자화: ', x)


# 원-핫 인코딩 방식으로 표현하면
from keras.utils import to_categorical

word_size = len(token.word_index) + 1
# token.word_index
x = to_categorical(x, num_classes=word_size)
print('문장의 원-핫 인코딩: \n', x)

문장의 토큰화:  {'오랫동안': 1, '꿈꾸는': 2, '자는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}
문장의 숫자화:  [[2, 5, 4, 1]]
문장의 원-핫 인코딩: 
 [[[0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]]]


In [41]:
import numpy
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Embedding
 
# 텍스트 리뷰 자료를 지정합니다.
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]


# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정합니다.
classes = array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

# 토큰화 
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n",  x)

# 패딩, 서로 다른 길이의 데이터를 4로 맞추어 줍니다.
padded_x = pad_sequences(x, 4)  
print("\n패딩 결과:\n", padded_x)

#임베딩에 입력될 단어의 수를 지정합니다.
word_size = len(token.word_index) +1
 
#단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력합니다.
model = Sequential()
model.add(Embedding(word_size, 8, input_shape=(4,)))
model.add(Flatten())
# model.add(Dense(512, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}

리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]

패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]
Epoch 1/20
1/1 [==============================] - 2s 2s/step - loss: 0.6927 - accuracy: 0.6000
Epoch 2/20
1/1 [==============================] - 0s 19ms/step - loss: 0.6905 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 18ms/step - loss: 0.6884 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 32ms/step - loss: 0.6862 - accuracy: 0.6000
Epoch 5/20
1/1 [==============================] - 0s 40ms/step - loss: 0.6840 - accuracy: 0.6000
Epoch 6/20
1/1 [==============

In [37]:
predict_review = '헐 헐랭 헐 배고파'

x = token.texts_to_sequences([predict_review])
padded_test_x = pad_sequences(x, 4) 

padded_test_x

array([[0, 0, 0, 0]])

In [38]:
model.predict(padded_test_x)

1/1 [==============================] - 0s 75ms/step


array([[0.47746846]], dtype=float32)

In [39]:
predict_review = '헐 헐랭 헐 배고파'

x = token.texts_to_sequences([predict_review])
padded_test_x = pad_sequences(x, 4) 

model.predict(padded_test_x)

1/1 [==============================] - 0s 72ms/step


array([[0.47746846]], dtype=float32)